FROM ubuntu:focal

VOLUME /flw

RUN apt-get update
RUN apt-get install -y \
    net-tools \
    iputils-ping \
    iproute2

RUN apt-get update
RUN apt-get install -y \
    mosquitto \
    sudo 


EXPOSE 1883
EXPOSE 8883

CMD /bin/bash