FROM ubuntu:22.04

VOLUME /flw

RUN apt-get clean

RUN apt-get update \
  && apt-get install -y net-tools \
  curl \
  iptables \
  iputils-ping \
  mosquitto \
  sudo 

# Ports used by Mosquitto host:
EXPOSE 1883
EXPOSE 8883

ENV CONTAINERNET_NESTED 1



